#! /bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin/
export PATH

mount -t ramfs none /var/


mkdir -p /var/etc
mkdir -p /var/media
mkdir -p /var/webroot
mkdir -p /var/etc/iproute
mkdir -p /var/run
mkdir -p /etc/udhcpc
mkdir -p /var/debug

cp -rf /etc_ro/* /etc/
cp -rf /webroot_ro/* /webroot/
umount -f /tmp
mount -t tmpfs none /tmp -o size=3M
mount -a

mount -t ramfs /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts
mdev -s
mkdir /var/run

echo '/sbin/mdev' > /proc/sys/kernel/hotplug
#echo 'sd[a-z][0-9] 0:0 0660 @/usr/sbin/autoUsb.sh $MDEV' >> /etc/mdev.conf
#echo 'sd[a-z] 0:0 0660 $/usr/sbin/DelUsb.sh $MDEV' >> /etc/mdev.conf
#echo 'lp[0-9] 0:0 0660 */usr/sbin/IppPrint.sh'>> /etc/mdev.conf
#wds rule start
#echo 'wds*.* 0:0 0660 */etc/wds.sh $ACTION $INTERFACE' > /etc/mdev.conf
#wsd rule end
echo 'sd[a-z][0-9] 0:0 0660 @/usr/sbin/usb_up.sh $MDEV $DEVPATH' >> /etc/mdev.conf
echo '-sd[a-z] 0:0 0660 $/usr/sbin/usb_down.sh $MDEV $DEVPATH'>> /etc/mdev.conf
echo 'sd[a-z] 0:0 0660 @/usr/sbin/usb_up.sh $MDEV $DEVPATH'>> /etc/mdev.conf
echo '.* 0:0 0660 */usr/sbin/IppPrint.sh $ACTION $INTERFACE'>> /etc/mdev.conf

insmod /lib/modules/gpio.ko
/etc/gpio_conf
insmod /lib/modules/phy_check.ko

mkdir -p /var/ppp
insmod /lib/modules/fastnat.ko 
insmod /lib/modules/kmbase.ko
echo "add;Wire:eth1" > /proc/km/wan_interface
insmod /lib/modules/fast_l2.ko 
insmod /lib/modules/bm.ko
#insmod /lib/modules/ai.ko 
insmod /lib/modules/mac_filter.ko 
#insmod /lib/modules/ip_mac_bind.ko
insmod /lib/modules/privilege_ip.ko
insmod /lib/modules/nos.ko
insmod /lib/modules/mac_group.ko
insmod /lib/modules/url_filter.ko
#insmod /lib/modules/loadbalance.ko
#insmod /lib/modules/app_filter.ko
#insmod /lib/modules/port_filter.ko
#insmod /lib/modules/arp_fence.ko
#insmod /lib/modules/ddos_ip_fence.ko
insmod /lib/modules/dnsredirect.ko
insmod /lib/modules/autodiscover.ko
insmod /lib/modules/kmwdog.ko
echo "enable 1 interval 30" >/proc/watchdog_cmd
echo 1 > /proc/fast_l2/br_enable
chmod +x /etc/mdev.conf

logdebug &